language: dart

dart:
  - dev

jobs:
  include:
    - name: "Analyzer"
      os: linux
      script: dart analyze --fatal-warnings --fatal-infos .
    - name: "Format"
      os: linux
      script: dartfmt -n --set-exit-if-changed .
    - name: "Tests"
      os: linux
      script: dart test --exclude-tags flaky
    - name: "Flaky Tests"
      os: linux
      script: dart test --tags flaky
  allow_failures:
    - name: "Flaky Tests"
      os: linux
      script: dart test --tags flaky

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
