name: http2
version: 2.0.0
description: A HTTP/2 implementation in Dart.
repository: https://github.com/dart-lang/http2

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  build_runner: ^1.10.0
  mockito: ^5.0.0-nullsafety
  test: ^1.16.0
  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
