name: http2
version: 1.0.2-dev
description: A HTTP/2 implementation in Dart.
repository: https://github.com/dart-lang/http2

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  mockito: ^5.0.0-nullsafety.1
  test: ^1.16.0-nullsafety.13
  pedantic: ^1.10.0-nullsafety.3
