name: http2
version: 2.3.0
description: A HTTP/2 implementation in Dart.
repository: https://github.com/dart-lang/http2

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.3.0
  lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.21.4
