name: http2
version: 2.0.0
description: A HTTP/2 implementation in Dart.
repository: https://github.com/dart-lang/http2

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.10.0
  mockito: ^5.0.0-nullsafety
  test: ^1.16.0
  pedantic: ^1.10.0
