name: http2
version: 2.0.1
description: A HTTP/2 implementation in Dart.
repository: https://github.com/dart-lang/http2

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  build_runner: '>=1.10.0 <3.0.0'
  lints: ^1.0.0
  mockito: ^5.0.16
  test: ^1.16.0
